### ISSUE TITLE
Commit SHA in footer is aligned awkwardly on mobile

### ISSUE THREAD

**Issue by neiljohari** [Syosset/Issues#3]
![screen shot 2017-07-10 at 10 48 08 am](https://user-images.githubusercontent.com/16354853/28023934-50b8e452-655d-11e7-83a0-c76297130d83.png)

**Comment by kailan** [comment]
Bit of a strange alignment on desktop too.
![image](https://user-images.githubusercontent.com/3542064/28025502-876ba808-658b-11e7-8836-da6a14eb1c36.png)

**Comment by neiljohari** [comment]
https://github.com/Syosset/Web/commit/c8bfc899151d3259e3d976d23e022c9ceae20b64
